#! /bin/sh

commands=(
	"xrdb merge .Xresources"
	"xset +fp /usr/share/fonts/misc"
	"xset fp rehash"
	"fc-cache -fv"
	"xset +dpms"
	"volnoti"
	"/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
	"nm-applet"
	"/usr/bin/gnome-keyring-daemon --start --components=ssh,secrets,pkcs11"
)

for cmd in "${commands[@]}"; do
	${cmd} &
done

dex -a -s ~/.config/autostart/ &
