#!/bin/sh
#     __                                          
#    / /_  _________ _      ______ ___  __________
#   / __ \/ ___/ __ \ | /| / / __ `__ \/ ___/ ___/
#  / /_/ (__  ) /_/ / |/ |/ / / / / / / /  / /__  
# /_.___/____/ .___/|__/|__/_/ /_/ /_/_/   \___/  
#           /_/                                   

#---[config]--------------------------------------------------------------------
#bspc config top_padding 35
bspc config border_width 2
bspc config window_gap 5

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config normal_border_color '#000000'
bspc config active_border_color '#464c4c'
bspc config focused_border_color '#aabbbc'
bspc config presel_feedback_color '#aabbbc'

bspc config click_to_focus true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4

#---[rules]---------------------------------------------------------------------
bspc rule -a '*' state=floating layer=normal

bspc rule -a Dunst state=floating layer=above sticky=on
bspc rule -a Termuake state=floating layer=above stick=on follow=on border=off

bspc rule -a Firefox -o desktop=alpha

#---[environment]---------------------------------------------------------------
[ "$XDG_CURRENT_DESKTOP" = "KDE" ] || \
[ "$XDG_CURRENT_DESKTOP" = "GNOME" ] || \
export QT_QPA_PLATFORMTHEME="qt5ct"

#---[autostart]-----------------------------------------------------------------
PATH="$HOME/.local/bin:$PATH"
sxhkd &

. "$HOME/.config/bspwm/daemons"
bspwm_mntrd
bspwm_walld
bspwm_termuaked

bspc config external_rules_command "$HOME/.config/bspwm/external-rules"

xsetroot -cursor_name left_ptr

/usr/bin/lxpolkit &
compton -b --backend xrender
feh --no-fehbg --bg-fill "$HOME/.local/share/wallpaper.png"

dunst & 

