#!/bin/sh

if [ "$(hostname)" = "laptop" ]; then
    bspc monitor eDP-1 -d 1
else
    bspc monitor DP-0 -d 1
    bspc monitor DP-2 -d 2
    bspc monitor DP-6 -d 3
fi

bspc config border_width 4
bspc config window_gap 6 

bspc config normal_border_color   '#000000'
bspc config active_border_color   '#464c4c'
bspc config focused_border_color  '#aabbbc'
bspc config presel_feedback_color '#aabbbc'

bspc config split_ratio 0.55
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Chromium desktop='^2'
bspc rule -a Pavucontrol state=floating

export QT_QPA_PLATFORMTHEME=qt5ct

set -U SXHKD_SHELL sh
sxhkd &

/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

picom -b

feh --bg-fill \
    "$HOME/.local/wallpaper/witcher1.jpg" \
    "$HOME/.local/wallpaper/witcher2.jpg" \
    "$HOME/.local/wallpaper/witcher3.jpg"

xsetroot -cursor_name left_ptr

killall -q polybar; \
    for m in $(polybar --list-monitors | cut -d ":" -f1); do \
        MONITOR=$m polybar -r default & done

