#!/bin/sh
PATH="$HOME/.local/bin:$PATH"

IGNORE="Termuake:Bspwm"
MAXIMIZE="Termuxton:Code - Firefox"
LEFT=""
RIGHT=""

wid="$1"
class="$2"

if echo "$IGNORE" | grep -q "$class"; then
    printf "\n"
elif xprop -id "$wid" _NET_WM_WINDOW_TYPE | grep -q _NET_WM_WINDOW_TYPE_DIALOG; then
    printf "\n"
elif echo "$MAXIMIZE" | grep -q "$class"; then
    printf "rectangle=%s\n" "$(grid --print -- "$wid" 0 0 12 12)"
elif echo "$LEFT" | grep -q "$class"; then
    printf "rectangle=%s\n" "$(grid --print -- "$wid" 0 0 12 6)"
elif echo "$RIGHT" | grep -q "$class"; then
    printf "rectangle=%s\n" "$(grid --print -- "$wid" 0 6 12 6)"
else
    printf "rectangle=%s\n" "$(grid --print -- "$wid" 1 1 10 10)"
fi
